server:
  port:8081
  undertow:
    direct-buffers: true
spring:
  datasource:
    url: jdbc:mysql:///mybatis
    username: root
    password: root1

mybatis:
  type-aliases-package: cn.itcast.service.pojo

